import "@repo/design-system/styles/globals.css";

import type { Metadata } from "next";
import { fonts } from "@repo/design-system/lib/fonts";
import { DesignSystemProvider } from "@repo/design-system/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={fonts}>
        <DesignSystemProvider>{children}</DesignSystemProvider>
      </body>
    </html>
  );
}
